metadata:
  labels:
    some-label: some-label-value
    class: KubernetesDeclarativeAgentTest
spec:
  containers:
    - name: build
      image: docker.hobot.cc/ci/gradle-builder:0.4
      command:
      - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: build
